## Import

In [1]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score

## IRIS Data Set importieren

In [2]:
# Load Dataset
df = pd.read_csv(r'C:\Users\srfzx\Downloads\ECG5000\ECG5000_TRAIN.csv', nrows=50000)
df2 = pd.read_csv(r'C:\Users\srfzx\Downloads\ECG5000\ECG5000_TEST.csv', nrows=50000)
df.shape


(500, 141)

In [3]:
y_train = df.target
X_train = df.drop(['target'],axis=1)
y_test = df2.target
X_test = df2.drop(['target'],axis=1)
X_test = df2.drop(['id'],axis=1)
X_test = X_test.drop(['target'],axis=1)

In [53]:
y_train.shape

(500,)

In [5]:
iris = datasets.load_iris()

In [68]:
feat_labels = ['att1','att2','Peath','Petal Width']

TypeError: 'DataFrame' object is not callable

In [34]:
X_train.head()

att1      att2      att3      att4      att5      att6      att7  \
0 -0.112522 -2.827204 -3.773897 -4.349751 -4.376041 -3.474986 -2.181408   
1 -1.100878 -3.996840 -4.285843 -4.506579 -4.022377 -3.234368 -1.566126   
2 -0.567088 -2.593450 -3.874230 -4.584095 -4.187449 -3.151462 -1.742940   
3  0.490473 -1.914407 -3.616364 -4.318823 -4.268016 -3.881110 -2.993280   
4  0.800232 -0.874252 -2.384761 -3.973292 -4.338224 -3.802422 -2.534510   

       att8      att9     att10  ...    att131    att132    att133    att134  \
0 -1.818286 -1.250522 -0.477492  ...  0.160348  0.792168  0.933541  0.796958   
1 -0.992258 -0.754680  0.042321  ...  0.560327  0.538356  0.656881  0.787490   
2 -1.490659 -1.183580 -0.394229  ...  1.284825  0.886073  0.531452  0.311377   
3 -1.671131 -1.333884 -0.965629  ...  0.491173  0.350816  0.499111  0.600345   
4 -1.783423 -1.594450 -0.753199  ...  0.966606  1.148884  0.958434  1.059025   

     att135    att136    att137    att138    att139    att140  
0  0.578621  0.257740  0.228077  0.123431  0.925286  0.193137  
1  0.724046  0.555784  0.476333  0.773820  1.119621 -1.436250  
2 -0.021919 -0.713683 -0.532197  0.321097  0.904227 -0.421797  
3  0.842069  0.952074  0.990133  1.086798  1.403011 -0.383564  
4  1.371682  1.277392  0.960304  0.971020  1.614392  1.421456  

[5 rows x 140 columns]

In [83]:
chaine =np.zeros(shape=(1,140))

In [84]:
chaine

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [105]:
chaine[0] = 5

In [107]:
chaine

array([[5., 5., 5., 3., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
        5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
        5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
        5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
        5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
        5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
        5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
        5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
        5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [106]:
chaine[0,3] = 3

In [110]:
k=0
for i in range(0,140):
    k=k+1
    chaine[0,i] = int(k)

In [111]:
chaine

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
         23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
         34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
         45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
         56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
         67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
         78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
         89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
        100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
        111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
        122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
        133., 134., 135., 136., 137., 138., 139., 140.]])

In [82]:
chaine =np.zeros(shape=(1,140))
for i in range(1,140):
    chaine = chaine + ""+ "att" + str(i)+"'"+","
print (chaine)
    
    

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

In [76]:
feat_labels = [chaine]

In [112]:
feat_labels = chaine

In [113]:
feat_labels

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
         23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
         34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
         45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
         56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
         67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
         78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
         89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
        100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
        111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
        122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
        133., 134., 135., 136., 137., 138., 139., 140.]])

## X_train view

## Data Split

In [8]:
X = df.drop(['target'], axis=1)

In [9]:
y = df.target

In [6]:
# Load Dataset
df = pd.read_csv(r'C:\Users\srfzx\Downloads\ECG5000\ECG5000_TRAIN.csv', nrows=50000)
df.shape

(500, 141)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)

## Random Forest Classifier

## test

In [67]:
feat_labels.dtypes

AttributeError: 'list' object has no attribute 'dtypes'

In [118]:
dirrabak=X_train.columns.values.tolist()

In [120]:
# RFC erstellen
clf = RandomForestClassifier(n_estimators=10000, random_state=0, n_jobs=-1)

# RFC antrainieren
clf.fit(X_train, y_train)

#Print the name and gini importance of each feature
for feature in zip(dirrabak, clf.feature_importances_):
  print(feature)

('att1', 0.0011014475957030982)
('att2', 0.0011617390592248975)
('att3', 0.0027440352888324065)
('att4', 0.011155642626652506)
('att5', 0.025891801697567454)
('att6', 0.0029292339669962815)
('att7', 0.0025594464162734987)
('att8', 0.0041592073199247384)
('att9', 0.005092813361708993)
('att10', 0.00738011392108558)
('att11', 0.010411494117858461)
('att12', 0.009647965108322769)
('att13', 0.002948267619504618)
('att14', 0.0015675469442347474)
('att15', 0.0012651062683758942)
('att16', 0.0009866345408598095)
('att17', 0.0012081125944659722)
('att18', 0.0013895380839372812)
('att19', 0.0012961564069668033)
('att20', 0.0015914798574326286)
('att21', 0.0018434694704880636)
('att22', 0.0019021561804005826)
('att23', 0.002311914341893938)
('att24', 0.003471269833398905)
('att25', 0.004209078225520273)
('att26', 0.0041364938920026295)
('att27', 0.004992144065999707)
('att28', 0.005280577185165576)
('att29', 0.006917441363085659)
('att30', 0.007729050463085196)
('att31', 0.011399914508487397)
('

In [121]:
#Gewicht erstellen
sfm = SelectFromModel(clf, threshold=0.01)

# Selector antrainieren
sfm.fit(X_train, y_train)

SelectFromModel(estimator=RandomForestClassifier(bootstrap=True,
                                                 class_weight=None,
                                                 criterion='gini',
                                                 max_depth=None,
                                                 max_features='auto',
                                                 max_leaf_nodes=None,
                                                 min_impurity_decrease=0.0,
                                                 min_impurity_split=None,
                                                 min_samples_leaf=1,
                                                 min_samples_split=2,
                                                 min_weight_fraction_leaf=0.0,
                                                 n_estimators=10000, n_jobs=-1,
                                                 oob_score=False,
                                                 random_state=0, verbose=0,
     

In [57]:
# RFC erstellen
clf = RandomForestClassifier(n_estimators=10000, random_state=0, n_jobs=-1)

# RFC antrainieren
clf.fit(X_train, y_train)

# Print the name and gini importance of each feature
for feature in zip(dirrabak, clf.feature_importances_):
    print(feature)

("'att1','att2','att3','att4','att5','att6','att7','att8','att9','att10','att11','att12','att13','att14','att15','att16','att17','att18','att19','att20','att21','att22','att23','att24','att25','att26','att27','att28','att29','att30','att31','att32','att33','att34','att35','att36','att37','att38','att39','att40','att41','att42','att43','att44','att45','att46','att47','att48','att49','att50','att51','att52','att53','att54','att55','att56','att57','att58','att59','att60','att61','att62','att63','att64','att65','att66','att67','att68','att69','att70','att71','att72','att73','att74','att75','att76','att77','att78','att79','att80','att81','att82','att83','att84','att85','att86','att87','att88','att89','att90','att91','att92','att93','att94','att95','att96','att97','att98','att99','att100','att101','att102','att103','att104','att105','att106','att107','att108','att109','att110','att111','att112','att113','att114','att115','att116','att117','att118','att119','att120','att121','att122','att123'

# feature gewicht feststellen

In [122]:
#Gewicht erstellen
sfm = SelectFromModel(clf, threshold=0.01)

# Selector antrainieren
sfm.fit(X_train, y_train)

SelectFromModel(estimator=RandomForestClassifier(bootstrap=True,
                                                 class_weight=None,
                                                 criterion='gini',
                                                 max_depth=None,
                                                 max_features='auto',
                                                 max_leaf_nodes=None,
                                                 min_impurity_decrease=0.0,
                                                 min_impurity_split=None,
                                                 min_samples_leaf=1,
                                                 min_samples_split=2,
                                                 min_weight_fraction_leaf=0.0,
                                                 n_estimators=10000, n_jobs=-1,
                                                 oob_score=False,
                                                 random_state=0, verbose=0,
     

## view feature die mehr als gewicht (0.15) haben 

In [123]:

for feature_list_index in sfm.get_support(indices=True):
    print(dirrabak[feature_list_index])

att4
att5
att11
att31
att32
att33
att34
att35
att103
att104
att105
att106
att107
att116
att117
att118
att119
att120
att121
att132
att133
att134
att135
att136
att137
att138


## Neue Data mit selektierten Features

## test 

In [124]:
X_important_train = sfm.transform(X_train)
X_important_test = sfm.transform(X_test)


In [125]:
df3 = pd.DataFrame(X_important_train)

In [128]:
X_important_train.shape

(500, 26)

In [14]:
X_important_train = sfm.transform(X_train)
X_important_test = sfm.transform(X_test)


## Retrain mit selektierten features

In [129]:
clf_important = RandomForestClassifier(n_estimators=10000, random_state=0, n_jobs=-1)
clf_important.fit(X_important_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10000,
                       n_jobs=-1, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

## beide Classifiers vergleichen

In [131]:
X_test.shape

(4500, 140)

In [130]:

y_pred = clf.predict(X_test )
accuracy_score(y_test, y_pred, normalize=True)

0.9364444444444444

In [132]:

y_important_pred = clf_important.predict(X_important_test)
accuracy_score(y_test, y_important_pred, normalize=True)

0.9333333333333333

## Scoring metrics

## Embedded 140 Features

In [134]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion='gini', random_state=42)
model = clf.fit(X_train,y_train)
predict = model.predict(X_test)
from sklearn.metrics import classification_report 
#print(classification_report(y_test, predict))
report = classification_report(y_test, predict, output_dict=True)
report = classification_report(y_test, predict, output_dict=True)
df = pd.DataFrame(report).transpose()
df

f1-score  precision    recall      support
1             0.969877   0.948019  0.992767  2627.000000
2             0.885417   0.917679  0.855346  1590.000000
3             0.410256   0.457143  0.372093    86.000000
4             0.288889   0.281081  0.297143   175.000000
5             0.058824   0.083333  0.045455    22.000000
accuracy      0.900667   0.900667  0.900667     0.900667
macro avg     0.522653   0.537451  0.512561  4500.000000
weighted avg  0.898403   0.897754  0.900667  4500.000000

## Embedded 26 Features

In [135]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion='gini', random_state=42)
model = clf.fit(X_important_train,y_train)
predict = model.predict(X_important_test)
from sklearn.metrics import classification_report 
#print(classification_report(y_test, predict))
report = classification_report(y_test, predict, output_dict=True)
report = classification_report(y_test, predict, output_dict=True)
df2 = pd.DataFrame(report).transpose()
df2

f1-score  precision    recall      support
1             0.953645   0.936834  0.971070  2627.000000
2             0.869903   0.896000  0.845283  1590.000000
3             0.310559   0.333333  0.290698    86.000000
4             0.213483   0.209945  0.217143   175.000000
5             0.046512   0.047619  0.045455    22.000000
accuracy      0.879778   0.879778  0.879778     0.879778
macro avg     0.478820   0.484746  0.473930  4500.000000
weighted avg  0.878547   0.878257  0.879778  4500.000000